---
# NOTE: below params are required in other roles.
- name: Set Elasticsearch users as a fact
  set_fact:
    elasticsearch_password: "{{ elasticsearch['elasticsearch_password'] | default(elasticsearch_password) }}"
    elasticsearch_kibanaserver_password: "{{ elasticsearch['kibanaserver_password'] | default(elasticsearch_kibanaserver_password) }}"
    elasticsearch_repoxplorer_password: "{{ elasticsearch['repoxplorer_password'] | default(elasticsearch_repoxplorer_password) }}"
    elasticsearch_logstash_password: "{{ elasticsearch['logstash_password'] | default(elasticsearch_logstash_password) }}"
    elasticsearch_curator_password: "{{ elasticsearch['curator_password'] | default(elasticsearch_curator_password) }}"
    elasticsearch_readonly_user: "{{ elasticsearch['readonly_user'] | default(elasticsearch_readonly_user) }}"
    elasticsearch_readonly_password: "{{ elasticsearch['readonly_password'] | default(elasticsearch_readonly_password) }}"
  no_log: true
