---
role_actions:
  - install
  - setup
  - backup
  - restore
  - get_logs
  - disable
  - upgrade

fqdn: "{{ fqdn }}"
backup: "{{ backup }}"

admin_password: "{{ auth.admin_password }}"

backup_method: "{{ backup.method }}"
backup_os_auth_url: "{{ backup.os_auth_url }}"
backup_os_auth_version: "{{ backup.os_auth_version }}"
backup_os_tenant_name: "{{ backup.os_tenant_name }}"
backup_os_username: "{{ backup.os_username }}"
backup_os_password: "{{ backup.os_password }}"

backup_swift_backup_container: "{{ backup.swift_backup_container }}"
backup_swift_backup_max_retention_secs: "{{ backup.swift_backup_max_retention_secs }}"

backup_scp_backup_host: "{{ backup.scp_backup_host }}"
backup_scp_backup_port: "{{ backup.scp_backup_port }}"
backup_scp_backup_user: "{{ backup.scp_backup_user }}"
backup_scp_backup_directory: "{{ backup.scp_backup_directory }}"
backup_scp_backup_max_retention_secs: "{{ backup.scp_backup_max_retention_secs }}"
