---
- name: Create state file
  file:
    path: /var/lib/software-factory/state/hound_config
    state: touch
  changed_when: false

- name: Check local config
  command: cat /var/lib/software-factory/state/hound_config
  register: localconfig
  changed_when: false

- name: Check upstream config
  command: git log -n 3 --oneline resources/
  args:
    chdir: /root/config
  register: upstreamconfig
  changed_when: false

- include_tasks: "{{ sf_tasks_dir }}/fetch_update_configuration.yml"
  vars:
    service_name: hound
    service_owner: hound
    service_group: hound
    service_config_dir: /etc/hound
    service_config_name: config.json
  when: localconfig.stdout != upstreamconfig.stdout

- name: Ensure service is started and enabled
  service:
    name: houndd
    state: started
    enabled: "yes"

- name: Write config repo sha1 matching current configuration
  copy:
    content: "{{ upstreamconfig.stdout }}"
    dest: /var/lib/software-factory/state/hound_config
  when: localconfig.stdout != upstreamconfig.stdout
