---
galaxy_info:
  description: Graphite-api
  company: Red Hat
  license: Apache
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - software-factory
