---
- include_tasks: "{{ sf_tasks_dir }}/check_version.yml"

- include_tasks: "{{ sf_tasks_dir }}/create_user.yml"
  vars:
    user_name: germqtt
    home_dir: /var/lib/germqtt
    ssh_key: zuul_rsa

- name: Create germqtt user
  user:
    name: "{{ user_name}}"
    shell: "/sbin/nologin"
    home: "{{ home_dir }}"
    create_home: true

- name: "Setup configuration"
  template:
    src: germqtt.conf.j2
    dest: /etc/germqtt/germqtt.conf
    mode: 0440
    group: germqtt
  register: germqtt_conf

- name: Ensure known_hosts file exists
  file:
    path: "/var/lib/germqtt/.ssh/known_hosts"
    owner: germqtt
    group: germqtt
    mode: 0600
    state: touch
  changed_when: false

- name: Check if the sources are already defined
  command: |
    ssh-keygen -f /var/lib/germqtt/.ssh/known_hosts -F [{{ gerrit_host }}:29418]
  register: _known_hosts_results
  failed_when: false
  changed_when: false

- name: Scan the missing sources
  shell: |
    ssh-keyscan -T 10 -p 29418 -t ssh-rsa {{ gerrit_host }} >> /var/lib/germqtt/.ssh/known_hosts
  when: _known_hosts_results.stdout == ""

- name: Restart service
  service:
    name: germqtt
    state: restarted
  when: germqtt_conf is changed

- name: Start service
  service:
    name: germqtt
    state: started
  when: not germqtt_conf is changed
