---
- name: restart zuul
  command: >
    /usr/share/sf-config/scripts/smart-restart.py zuul
        --url {{ zuul_web_url }}
        --sender root@{{ fqdn }}
        --mail {{ network.admin_mail_forward }}
        {{ zuul_services|join(" ") }}
  register: _zuul_restart_script
  failed_when: _zuul_restart_script.rc not in [0, 3]
  changed_when: _zuul_restart_script.rc == 3
