---
- name: Install graphite-api packages
  yum:
    name: '{{ item }}'
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
  with_items: "{{ graphite_api_packages }}"
