---
- include_tasks: "{{ sf_tasks_dir }}/create_user.yml user_name=rabbitmq"

- name: Check mnesia directory
  stat:
    path: /var/lib/rabbitmq/mnesia/
  register: mnesia

- name: Reset data
  when: mnesia.stat.isdir is undefined
  command: rabbitmqctl force_reset
  ignore_errors: "yes"
  no_log: true

- name: Set rabbitmq heartbeat timeout
  replace:
    dest: /etc/rabbitmq/rabbitmq.config
    regexp: ".*{heartbeat, 600}.*"
    replace: "   {heartbeat, 3600}"

- name: Start rabbitmq
  service:
    name: rabbitmq-server
    state: started
    enabled: "yes"

- name: Create vhosts
  rabbitmq_vhost:
    name: "{{ item.vhost }}"
    state: present
  with_items: "{{ rabbitmq_users }}"

- name: Create users
  rabbitmq_user:
    user: "{{ item.name }}"
    vhost: "{{ item.vhost }}"
    password: "{{ item.password }}"
    configure_priv: .*
    write_priv: .*
    read_priv: .*
    state: present
    node: rabbit
  with_items: "{{ rabbitmq_users }}"
