role_actions:
  - install
  - setup
  - get_logs
  - disable

storyboard_service_token: "CHANGE_ME"

storyboard_mysql_host: "mysql.example.com"
storyboard_mysql_port: 3306
storyboard_mysql_db: "storyboard"
storyboard_mysql_user: "storyboard"
storyboard_mysql_password: "CHANGE_ME"

storyboard_email_notification: True
storyboard_rabbitmq_password: "CHANGE_ME"

storyboard_api_workers: 1

storyboard_services:
  - storyboard
  - storyboard-worker
