---
galaxy_info:
  description: Firehose service and mqtt-triggered hooks
  company: Red Hat
  license: Apache
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - software-factory
dependencies:
  - role: sf-mosquitto
