---
role_actions:
  - stop
  - install
  - setup
  - backup
  - restore
  - update
  - upgrade
  - get_logs
  - disable

zuul3_services:
  - rh-python35-zuul-scheduler
  - rh-python35-zuul-merger
  - rh-python35-zuul-executor
  - rh-python35-zuul-web

zuul3_scheduler_packages:
  - rh-python35-zuul
  - rh-python35-zuul-scheduler
  - rh-python35-zuul-webui
  - httpd
  - sf-web-assets

zuul3_merger_packages:
  - rh-python35-zuul
  - rh-python35-zuul-merger
  - httpd

zuul3_executor_packages:
  - rh-python35-zuul
  - rh-python35-zuul-executor
  - rh-python35-ara

zuul3_web_packages:
  - rh-python35-zuul
  - rh-python35-zuul-web

zuul3_conf_dir: "/etc/opt/rh/rh-python35/zuul"
zuul3_lib_dir: "/var/opt/rh/rh-python35/lib/zuul"
zuul3_log_dir: "/var/opt/rh/rh-python35/log/zuul"
zuul3_share_dir: "/opt/rh/rh-python35/root/usr/share/javascript/zuul"
zuul3_sysconfig: "/etc/opt/rh/rh-python35/sysconfig/zuul"

zuul3_port: 8085
zuul3_webapp_port: 8003
zuul3_web_port: 9003
zuul3_gearman_port: 4733

zuul3_mysql_host: "mysql.example.com"
zuul3_mysql_port: 3306
zuul3_mysql_db: "zuul3"
zuul3_mysql_user: "zuul3"
zuul3_mysql_password: "CHANGE_ME"

gerrit_pub_url: "https://example.com/r/"
zuul3_pub_url: "https://example.com/zuul3/"
zuul3_internal_url: "http://localhost:{{ zuul3_port }}/"

zuul3_loglevel: INFO
zuul3_root_loglevel: WARNING

# We need those variables to generate config-check nodepool.yaml file
nodepool3_conf_dir: "/etc/opt/rh/rh-python35/nodepool"
nodepool3_lib_dir: "/var/opt/rh/rh-python35/lib/nodepool"
nodepool3_webapp_port: 8006

zuul3_periodic_pipeline_mail_rcpt: root@localhost
