---
galaxy_info:
  author: Openstack Contributors
  description: Openstack Log Processing tools
  company: Openstack
  license: Apache
  min_ansible_version: 2.9
  platforms:
    - name: Centos
      versions:
        - 8
  galaxy_tags: []
dependencies: []
