---
- name: "Dump databases"
  shell: mysqldump --all-databases | gzip > /var/log/mariadb/dump.gz

- name: "Fetch mariadb logs"
  synchronize:
    mode: pull
    src: /var/log/mariadb/
    dest: "{{ log_dest }}/log"
  ignore_errors: true
