---
- name: nodepool3 restart
  command: >
    /usr/share/sf-config/scripts/smart-restart.py nodepool3
        --url {{ nodepool3_internal_url }}
        --sender root@{{ fqdn }}
        --mail {{ network.admin_mail_forward }}
        {{ nodepool3_services|join(" ") }}
  register: _nodepool3_restart_script
  failed_when: _nodepool3_restart_script.rc not in [0, 3]
  changed_when: _nodepool3_restart_script.rc == 3
