---
galaxy_info:
  description: Monit setup and handlers for software factory
  company: Red Hat
  license: Apache
  min_ansible_version: 2.2
  platforms:
    - name: EL
      version:
        - 7
  galaxy_tags:
    - software-factory
dependencies:
  - role: sf-handlers
