---
galaxy_info:
  description: RepoXplorer charts and stats for Git repositories
  company: Red Hat
  license: Apache
  min_ansible_version: 2.2
  platforms:
    - name: EL
      version:
        - 7
  galaxy_tags:
    - software-factory
