---
- name: Create user
  include_tasks: "{{ sf_tasks_dir }}/create_user.yml user_name=pagesuser shell=/bin/sh"

- name: Create logs directory
  file:
    path: /var/www/html/pages
    state: directory
    owner: pagesuser
    group: apache
    mode: 0755

- name: Install resources2pages.py
  copy:
    src: files/resources2pages.py
    dest: /usr/local/bin/resources2pages.py
    mode: 0755

- name: Authorize pagesuser sshkey
  authorized_key:
    user: pagesuser
    key: "{{ item }}"
  with_items: "{{ pagesuser_authorized_keys }}"
