---
- name: Disable service
  service:
    name: "rh-python35-{{ item }}"
    state: stopped
    enabled: "no"
  with_items: "{{ nodepool3_services }}"
  ignore_errors: "yes"

- block:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/httpd/conf.d/nodepool3_log.conf
        - /var/www/nodepool3-log
        - "{{ nodepool3_lib_dir }}"
        - "{{ nodepool3_conf_dir }}"

    - name: Remove packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items: "{{ nodepool3_launcher_packages }} + {{ nodepool3_builder_packages }}"
  when: erase == True
