- name: Disable service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: "{{ nodepool3_services }}"
  ignore_errors: yes

- block:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/httpd/conf.d/nodepool3_log.conf
        - /var/www/nodepool3-log
        - /var/lib/nodepool
        - /etc/nodepool
        - /var/log/nodepool

    - name: Remove packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items: "{{ nodepool3_packages }}"
  when: erase == True
