---
role_actions:
  - install
  - setup
  - update
  - upgrade
  - get_logs
  - disable

nodepool3_services:
  - rh-python35-nodepool-launcher
  - rh-python35-nodepool-builder

nodepool3_launcher_packages:
  - rh-python35-nodepool
  - rh-python35-nodepool-launcher

nodepool3_builder_packages:
  - rh-python35-nodepool
  - rh-python35-nodepool-builder
  - sf-elements
  - httpd

nodepool3_cache_ttl: 5
nodepool3_providers:
  - name: default
    api_timeout: 60
    auth_url: http://localhost:35357/v2.0
    project_name: tenantname
    username: username
    password: secret
    region_name: regionOne

nodepool3_conf_dir: "/etc/opt/rh/rh-python35/nodepool"
nodepool3_lib_dir: "/var/opt/rh/rh-python35/lib/nodepool"
nodepool3_log_dir: "/var/opt/rh/rh-python35/log/nodepool"
nodepool3_sysconfig: "/etc/opt/rh/rh-python35/sysconfig/nodepool"

nodepool3_webapp_port: 8006

nodepool_loglevel: INFO
nodepool_root_loglevel: WARNING
