---
- include_tasks: "{{ sf_tasks_dir }}/check_version.yml"

- include_tasks: "{{ sf_tasks_dir }}/create_user.yml user_name=storyboard"

- name: "Install storyboard.conf"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/storyboard/{{ item }}"
    owner: storyboard
    group: storyboard
    mode: 0400
  loop:
    - storyboard.conf
    - superuser.yaml
    - service_token.sql
  notify: restart storyboard

- name: "Install storyboard sysconfig file"
  template:
    src: storyboard.j2
    dest: /etc/sysconfig/storyboard
    mode: 0644

- name: "Setup database"
  command: storyboard-db-manage upgrade head
  changed_when: false

- name: "Setup superusers"
  command: storyboard-db-manage load_superusers /etc/storyboard/superuser.yaml
  changed_when: false

- name: "Setup service_token"
  command: bash -c "mysql storyboard < /etc/storyboard/service_token.sql"
  changed_when: false

- name: Start service
  service:
    name: "{{ item }}"
    state: started
    enabled: "yes"
  loop: "{{ storyboard_services }}"
