---
role_actions:
  - install
  - setup
  - get_logs
  - disable
  - upgrade

hash_code: |
    import crypt, random, string, sys
    salt = '\$6\$' + ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(16)) + '\$'
    sys.stdout.write(crypt.crypt(

hash_code_end: ", salt))"

cauth_mysql_db: "cauth"
cauth_mysql_host: "mysql.example.com"
cauth_mysql_password: "CHANGE_ME"
cauth_mysql_port: 3306
cauth_mysql_user: "cauth"

sf_service_user_password: "CHANGE_ME"
