---
role_actions:
  - install
  - setup
  - get_logs
  - disable
  - update

role_package: python3-cauth

cauth_loglevel: INFO
cauth_root_loglevel: WARNING

cauth_mysql_db: "cauth"
cauth_mysql_host: "mysql.example.com"
cauth_mysql_password: "CHANGE_ME"
cauth_mysql_port: 3306
cauth_mysql_user: "cauth"
