---
- include_tasks: "{{ sf_tasks_dir }}/check_version.yml"
- name: Execute upgrade tasks
  service:
    name: log-gearman-client
    state: stopped
  when: _version is changed
- include_tasks: "{{ sf_tasks_dir }}/write_version.yml"

- include_tasks: "{{ sf_tasks_dir }}/create_user.yml user_name=joblogsclient"

- name: Install log gearman client configuration
  template:
    src: templates/log-client.yaml.j2
    dest: /etc/log-gearman-client/config.yml
    owner: joblogsclient
    group: joblogsclient
  register: config

- name: Start service
  service:
    name: log-gearman-client
    state: started
    enabled: "yes"

- name: Restart log gearman client if needed
  service:
    name: log-gearman-client
    state: restarted
  when: config is changed
