---
- name: "Copy a backup of arch.yaml file"
  command: cp /etc/software-factory/arch.yaml /etc/software-factory/arch-backup.yaml

- name: "Backup data"
  synchronize:
    mode: pull
    src: "{{ item }}"
    dest: "{{ backup_dest }}/"
    delete: yes
    rsync_opts: --relative
  with_items:
    - /etc/software-factory/sfconfig.yaml
    - /etc/software-factory/logo-splash.png
    - /etc/software-factory/logo-topmenu.png
    - /etc/software-factory/logo-favicon.ico
    - /var/lib/software-factory/bootstrap-data
    - /root/config
    - /etc/software-factory/arch-backup.yaml
