---
- block:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/cauth
        - /etc/httpd/conf.d/cauth.site
        - /var/lib/cauth/keys/privkey.pem

    - name: Remove packages
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - python3-cauth
  when: erase == True
